apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager-show-me-the-minutes
  namespace: "argocd"
spec:
  destination:
    name: show-me-the-minutes
    namespace: cert-manager
  project: default
  source:
    chart: cert-manager
    helm:
      values: |-
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::746669190615:role/K1-show-me-the-minutes-cert-manager
        installCRDs: true
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
