apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-secrets-show-me-the-minutes-components
  namespace: "argocd"
spec: 
  destination:
    name: show-me-the-minutes
    namespace: external-secrets
  project: default
  source:
    path: registry/clusters/show-me-the-minutes/external-secrets
    repoURL: https://github.com/kubefirst-demo-bot/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
