apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-secrets-operator-paas-me-components
  namespace: "argocd"
spec: 
  destination:
    name: paas-me
    namespace: external-secrets-operator
  project: default
  source:
    path: registry/clusters/paas-me/cluster-secret-store
    repoURL: https://github.com/kubefirst-demo-bot/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
