name: Publish Image
on: 
  workflow_dispatch:
  push:
    branches:
      main

permissions:
  id-token: write

env:
  AWS_REGION: "us-east-2"
  # update role ARN
  ASSUME_ROLE_ARN: "arn:aws:iam::126827061464:role/github-action-oidc-pass-app-repo"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # TODO remove below block
        with:
          repository: "jarededwards/zippy"
          ref: "main"
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ env.ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # fix this upstream. or have a place holder
      - name: replace remote registry
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -i "s/ghcr.io\/jarededwards/$ECR_REGISTRY\/konstructio/g" .goreleaser.yaml
          cat .goreleaser.yaml

      - name: push-image
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> 2"
          args: release --skip=validate,archive --clean


  update-{clusterName}:
    name: "update-chart-{clusterName}"
    runs-on: ubuntu-latest
    needs: 
      - pulish-image
    env:
      ECR_REGISTRY: ${{ needs.publish-image.outputs.registry }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: print-version
        run: echo "Updating paas-api chart to $IMAGE_TAG"
      
      - name: checkout-gitops
        uses: actions/checkout@v4
        with:
          # TODO: remove hardcoded gitops repo
          repository: "kubefirst-demo-bot/gitops"
          ref: main
          token: ${{ secrets.KBOT_TOKEN }}         
                      
      - name: update-image-tag
        run: |
          sed "s/repository:.*/repository: $ECR_REGISTRY\/{appName}/" -i registry/clusters/{clusterName}/{appName}.yaml
          sed "s/tag:.*/tag: $IMAGE_TAG/" -i registry/clusters/{clusterName}/{appName}.yaml

      - name: configure-git
        run: |
          git config --global user.email "konstruct-bot@konstruct.io"
          git config --global user.name "konstruct-bot"

      - name: commit-and-push
        run: |
          # TODO change the cluster name
          git add   registry/clusters/{clusterName}/{appName}.yaml
          git commit -m "[skip ci]: upgrade {appName} chart to $IMAGE_TAG in {clusterName}"

          git push origin main
          
          git push origin main
          