name: Add new application

on:
  workflow_dispatch:
    inputs:
      app_repo:
        description: 'Application repistory'
        required: true
      cluster_name:
        description: 'Cluster name'
        required: false
  push:
    branches:
      muse-sisay/001

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    # skip this for now
    env:
      CLUSTER_NAME : ${{inputs.cluster_name}}
      APP_REPO : ${{inputs.app_repo}}
    steps:
      - name: Validate cluster
        run: echo "Validating $CLUSTER_NAME"
      - name: Validate repository
        run: echo "Validating $APP_REPO"

  create-argo-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: 
      - validate-inputs
    env:
      CLUSTER_NAME : ${{inputs.cluster_name}}
      APP_REPO : ${{inputs.app_repo}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: create argo app
        run: |
          # this assumes the endpoint is https:///
          APP_NAME=$(echo "$APP_REPO" | cut -d / -f 5 | sed 's/\.git//' )

          cp ./templates/argo-app.yaml ./registry/clusters/${CLUSTER_NAME}/${APP_NAME}.yaml
          
          # replace {clusterName}
          sed "s/{clusterName}/$CLUSTER_NAME/g" -i ./registry/clusters/${CLUSTER_NAME}/${APP_NAME}.yaml

          # replace {appName}
          sed "s/{appName}/$APP_NAME/g" -i ./registry/clusters/${CLUSTER_NAME}/${APP_NAME}.yaml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER_NAME : ${{inputs.cluster_name}}
          APP_REPO : ${{inputs.app_repo}}
        run: |
          APP_NAME=$(echo "$APP_REPO" | cut -d / -f 5 | sed 's/\.git//' )

          git config user.name "github-actions[bot]"
          git config user.email "general@konstruct.io"
          git add --all
          git commit -m "[skip-ci] add $APP_NAME in $CLUSTER_NAME" || echo "No changes to commit"
          git push origin HEAD

  # change the name
  copy-over-ci:
  # what auth should we use
    runs-on: ubuntu-latest
    # needs:
    #   - validate-inputs
    steps:
      - name: Extract owner/repo
        id: extract_repo
        run: |
          # TODO remove hardcoded repo name
          APP_REPO="https://github.com/kubefirst-demo-bot/zippy"
          stripped=$(echo "https://github.com/kubefirst-demo-bot/zippy" | cut -d / -f 4,5)
          echo "owner_repo=$stripped" >> $GITHUB_OUTPUT


      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          path: gitops

      - name: Check app repository code
        uses: actions/checkout@v4
        with:
          repository: ${{steps.extract_repo.outputs.owner_repo}}
          path: app
          token: ${{secrets.KBOT_TOKEN}}
      

      - name: create workflow, docker file, and charts
        env:
          APP_REPO : ${{inputs.app_repo}}
          CLUSTER_NAME : ${{inputs.cluster_name}}
        run: |

          APP_NAME=$(echo "$APP_REPO" | cut -d / -f 5 | sed 's/\.git//' )

          cp gitops/templates/Dockerfile app/Dockerfile

          # TODO create the directory if it doesn't exist
          mkdir -p app/.github/workflows
          cp gitops/templates/actions/publish-image.yaml app/.github/workflows/publish-image.yaml
          # replace {clusterName}
          sed "s/{clusterName}/$CLUSTER_NAME/g" -i app/.github/workflows/publish-image.yaml
          sed "s/{appName}/$APP_NAME/g" -i app/.github/workflows/publish-image.yaml

          cp gitops/templates/actions/publish-chart.yaml app/.github/workflows/publish-chart.yaml
          sed "s/{clusterName}/$CLUSTER_NAME/g" -i app/.github/workflows/publish-chart.yaml
          sed "s/{appName}/$APP_NAME/g" -i app/.github/workflows/publish-chart.yaml

          mkdir -p "app/charts/$APP_NAME"
          cp -r gitops/templates/charts/* "app/charts/$APP_NAME/"

      
      - name: Commit and push changes
        env:
          # TOKEN needs to be update
          GITHUB_TOKEN: ${{ secrets.KBOT_TOKEN }}
          CLUSTER_NAME : ${{inputs.cluster_name}}
          APP_REPO : ${{inputs.app_repo}}
        run: |
          cd ./app
          git config user.name "github-actions[bot]"
          git config user.email "general@konstruct.io"
          git add --all
          git commit -m "add $APP_NAME in $CLUSTER_NAME" || echo "No changes to commit"
          git push origin HEAD
