name: copy ci

env:
  AWS_REGION: "us-east-2"
  # update role ARN
  ASSUME_ROLE_ARN: "arn:aws:iam::746669190615:role/github-action-oidc-paas-app-repo"

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application repository name'
        required: true
        default: 'zippy2'
      cluster_name:
        description: 'Cluster name'
        default: 'show-me-the-minutes'
        required: true
  # push:
  #   branches:
  #     - main

jobs:
  # validate-inputs:
  #   runs-on: ubuntu-latest
  #   env:
  #     CLUSTER_NAME: ${{inputs.cluster_name}}
  #     APP_NAME: ${{inputs.app_name}}
  #   steps:
  #     - name: Validate cluster
  #       run: echo "Validating $CLUSTER_NAME"
  #     - name: Validate app name
  #       run: echo "Validating $APP_NAME"

  copy-ci:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: ${{inputs.cluster_name}}
      APP_NAME: ${{inputs.app_name}}
    steps:
      - name: Checkout gitops repository
        uses: actions/checkout@v4
        with:
          path: gitops

      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.app_name}}
          path: app
          token: ${{secrets.KBOT_TOKEN}}

      - name: create chart and github workflows
        run: |
          cd ./app
          DIR="./charts"

          # Check if directory exists
          if [ -d "$DIR" ]; then
            echo "directory $DIR exists skipping helm chart creation"
          else
            echo "directory $DIR does not exist. Creating now..."
            mkdir -p "$DIR"
            cd "$DIR"
            helm create $APP_NAME
            cd ..
          fi
          
          mkdir -p .github/workflows
          cp ../gitops/templates/actions/publish.yaml .github/workflows/publish.yaml
          cp ../gitops/templates/actions/deploy.yaml .github/workflows/deploy.yaml
          echo replace cluster name and app name
          # sed "s/{clusterName}/$CLUSTER_NAME/g" -i .github/workflows/publish.yaml
          sed "s#{appName}#$APP_NAME#g" -i .github/workflows/publish.yaml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.KBOT_TOKEN }}
          APP_NAME: ${{inputs.app_name}}
        run: |
          cd ./app
          git config user.name "kubefirst-demo-bot"
          git config user.email "general@konstruct.io"
          git add --all
          git commit -m "add ci content for $APP_NAME" || echo "No changes to commit"
          git push origin main

